"""initial schema - all 13 tables

Revision ID: 86d8f3762447
Revises: 
Create Date: 2026-03-11 19:04:14.578196
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '86d8f3762447'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_models',
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('calibration_type', sa.String(length=20), nullable=False),
    sa.Column('training_window', sa.String(length=100), nullable=True),
    sa.Column('calibration_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_uri', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('model_version', 'calibration_type')
    )
    op.create_table('features_snapshot',
    sa.Column('snapshot_id', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('as_of_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_session_date', sa.Date(), nullable=False),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('momentum_5d', sa.Float(), nullable=True),
    sa.Column('momentum_10d', sa.Float(), nullable=True),
    sa.Column('rolling_return_5d', sa.Float(), nullable=True),
    sa.Column('rolling_return_20d', sa.Float(), nullable=True),
    sa.Column('rolling_volatility_20d', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('sector_return_1d', sa.Float(), nullable=True),
    sa.Column('sector_return_5d', sa.Float(), nullable=True),
    sa.Column('benchmark_relative_return_1d', sa.Float(), nullable=True),
    sa.Column('news_sentiment_24h', sa.Float(), nullable=True),
    sa.Column('news_sentiment_7d', sa.Float(), nullable=True),
    sa.Column('vix_level', sa.Float(), nullable=True),
    sa.Column('sp500_momentum_200d', sa.Float(), nullable=True),
    sa.Column('regime_label', sa.String(length=30), nullable=True),
    sa.Column('dataset_version', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('macro_series',
    sa.Column('series_id', sa.String(length=50), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('release_time_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('series_id', 'observation_date')
    )
    op.create_table('market_bars_daily',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('as_of_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_table('market_calendar',
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('open_time_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_time_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('early_close_flag', sa.Boolean(), nullable=True),
    sa.Column('is_holiday', sa.Boolean(), nullable=True),
    sa.Column('next_trading_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('exchange', 'session_date')
    )
    op.create_table('model_registry',
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=64), nullable=True),
    sa.Column('algorithm', sa.String(length=50), nullable=True),
    sa.Column('training_window_start', sa.Date(), nullable=True),
    sa.Column('training_window_end', sa.Date(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('model_version')
    )
    op.create_table('news_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('published_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('event_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('credibility_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('paper_trades',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('position_qty', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('transaction_cost', sa.Float(), nullable=True),
    sa.Column('slippage_cost', sa.Float(), nullable=True),
    sa.Column('daily_pnl', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('run_id', 'date', 'symbol')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('as_of_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('probability_up', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('top_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('feature_snapshot_id', sa.String(length=128), nullable=True),
    sa.Column('dataset_version', sa.String(length=64), nullable=True),
    sa.Column('cache_ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('realized_direction', sa.String(length=10), nullable=True),
    sa.Column('realized_return', sa.Float(), nullable=True),
    sa.Column('outcome_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_table('quarantine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('record_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('starting_capital', sa.Float(), nullable=False),
    sa.Column('min_confidence_trade', sa.Float(), nullable=True),
    sa.Column('max_position', sa.Float(), nullable=True),
    sa.Column('transaction_cost_bps', sa.Float(), nullable=True),
    sa.Column('slippage_bps', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('symbols',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('avg_daily_volume_30d', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('news_symbol_mapping',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['news_events.event_id'], ),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], ),
    sa.PrimaryKeyConstraint('event_id', 'symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_symbol_mapping')
    op.drop_table('symbols')
    op.drop_table('simulation_runs')
    op.drop_table('quarantine')
    op.drop_table('predictions')
    op.drop_table('paper_trades')
    op.drop_table('news_events')
    op.drop_table('model_registry')
    op.drop_table('market_calendar')
    op.drop_table('market_bars_daily')
    op.drop_table('macro_series')
    op.drop_table('features_snapshot')
    op.drop_table('calibration_models')
    # ### end Alembic commands ###
